### ISSUE TITLE
Total yield decreases over time?

### ISSUE THREAD

**Issue by wtanksleyjr** [jensb89/anchor-earnings#2]
I emptied Anchor a while ago, and now that I've come back I find that anchor-earnings computes my total interest earned as lower than when I pulled my money out -- as though Anchor gave negative interest! The graph literally shows me losing total interest earned, a downward slope.

I'm sure it's because of my aUST transfer, of course. Yeah, I'm THAT GUY. So thank you for doing all of this work :) !

Let me know if you want my wallet or anything.

**Comment by jensb89** [comment]
Hm strange, I thought this problem was solved already 😅 I will look into it as soon as I find some time (probably the end of the week)

**Comment by wtanksleyjr** [comment]
Hey, good/bad news (not sure which): flipsidecrypto does exactly the same thing, it shows me losing money ever since I pulled all my money out. Both show my current deposit being a negative number.

**Comment by jensb89** [comment]
Okay, I had a short look, I also found one test wallet with a slightly negative "holdings" amount (+ also negative aUst holding)
The info regarding flipsidecrypto is actually good news, it tells us there is no bigger logic problem in the code here. At least not compared to flipsidecrpyto.

However, there seems to be something both are not taken into account. 
Things that are not fully considered in my code are services like "Mirror" etc. However, flipside crpyto at least takes "mirror holdings" into account and shows the same negative number in aUST holdings.

Thus, there must be a source of aUST that both do not consider.
The main problem: When (additional, not known) aUST is spent/burnt to UST we will have a negative balance of aUST and negative anchor UST holdings.

The big question is: where does this extra aUST comes from? :) We already included aUST transfers from one wallet to another. So I believe that's not the problem here. 

For my test wallet it seems **the problem might be if some mirror Asset (like mAAPL) was not retrieved with aUST but by transfering from another wallet or swapping with UST and then at some later time, the mirror Asset was converted to aUST**. 

**Could this be the case for you too?**

If so, I think I could implement a check for that in the code somehow, so that also aUST converted from other sources is considered in the overall holdings calculation.

Idea: If no anchor deposit/redemption or aUst transfer is found, loop through all "from_contract" event logs and check for the following pattern:
```
{
  key: "contract_address",
  value: "terra1hzh9vpxhsk8253se0vv5jj6etdvxu3nv8z07zu"  --> the aUST contract
},
{ 
  key: "action",
  value: "transfer"
},
{
  key: "from",
  value: "somewhere" (e.g. mirror Contract)
},
{
  key: "to",
  value: "OUR WALLET"
},
{
  key: "amount",
  value: "some value" (the aUST amount we received)
}
```
This should take care of all additional aUST incomes :)

**Comment by jensb89** [comment]
I pushed a fix. At least for my test wallet this solved it. Please let me know if it is fixed for you as well. Otherwise, there might be another source of aUST we are not thinking about...

**Comment by wtanksleyjr** [comment]
I think that might be it -- I actually arbitraged aUST on Loop one time (it
wasn't very much, their liquidity is shallow so you can't profit enough to
make it worth it). So when I emptied my Anchor, it actually converted aUST
that I never minted to UST.

I don't know for sure what a fix might be, but it seems that at least it
would be better if you floored the UST calculation at zero. Anchor can
never hold an equivalent to negative USTs, after all.

-Wm

**Comment by jensb89** [comment]
Exactly, it should be 0. Is it working now, or is it still negative for you? My test wallet is exactly 0 now. If not I might have to look into loop contracts ...

**Comment by wtanksleyjr** [comment]
It looks great now, it's definitely the correct amount deposited (of course
I couldn't even guess about whether it's the correct amount of interest).
Thank you!

**Comment by jensb89** [comment]
Awesome 🙂
Glad I could help. Thanks for opening the issue :)

**Comment by jensb89** [comment]
Short update here: The implemented fix seems to take up a lot more computational time (due to the string comparison) and leads to some timeouts at Heroku for wallets with a lot of transactions.

I changed the default back to the way it was before, however, you can call the url now with a /full at the end to search the complete dataset. E.g. http://anchor-earnings.herokuapp.com/address/<address>/full

Will think about better handling of these cases to decrease computational time and make it the default...
